function [IDn,PIDn] = PID(i,u,controller)
IDn=zeros(t);
PIDn=zeros(t);
Ip_1=0.5;
Ip_2=0.5;
In_1=0;
ID_1=0;
for n =1:controller.sim_time
    Pn=controller.Kp*(controller.SG(n)-controller.target);
    In=controller.In_1+controller.Kp/(controller.Ti*(controller.SG(n)-controller.target));
    Dn=controller.Kp*controller.Td*(controller.SG(n)-controller.SG(n-1)/(n-(n-1)));
    PIDn(n)=Pn+In+Dn;
    Ipn=controller.k0*controller.ID_1+controller.k1*controller.Ip_1-controller.k2*controller.Ip_2;
    IDn(n)=(1+controller.gamma)*PIDn-(controller.gamma*controller.Ip_1);
    Ip_2=controller.In_1;
    Ip_1=Ipn;
    In_1=In;
    ID_1=IDn(n);
end